updateCounter method (bug correction): append counter only once
sapegin/social-likes pull request #209
Opened 2017-11-05 18:52 UTC by RunnX

There was a bug in the updateCounter method that added a counter element even if the widget already had a counter element.  This would result in two counters showing up for one social widet (Facebook 0 0).

2017-11-06 13:23 UTC, sapegin requested changes
Thanks for the PR!

2017-11-06 13:23 UTC, sapegin commented on src/styles/flat/font/social-likes.styl
> +	src:url("data:application/x-font-woff;charset=utf-8;base64,d09GRk9UVE8AABZcAAoAAAAAIxgAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABDRkYgAAAC1AAAE1wAAB4oltsOeUZGVE0AABYwAAAAGgAAAByB7q+eT1MvMgAAAUgAAABKAAAAYEDWXU9
Please remove changes in this file, there are not related to your PR.

2017-11-07 08:15 UTC, sapegin commented
Almost, now there’s a whitespace change in that styl file ;-|

2017-11-16 19:49 UTC, RunnX commented
@sapegin - I think the issue is now resolved.

2017-11-17 08:07 UTC, sapegin approved these changes

2017-11-17 08:07 UTC, merged

2017-11-17 08:08 UTC, sapegin commented
Thanks, merged!